### ISSUE TITLE
Add new 3rd parties to implemented list

### ISSUE THREAD

**Issue by MatthewTheall** [green-button/green-button.github.io#46]
eMeter- A Siemens business http://www.emeter.com/
Sun Run http://www.sunrun.com/
Echodog http://ecodoginc.com/
Hawaiian Electric http://www.hawaiianelectric.com/portal/site/heco
Maui Electric http://www.hawaiianelectric.com/portal/site/heco
Hawai'i Electric Light http://www.hawaiianelectric.com/portal/site/heco
Seattle City Light http://www.seattle.gov/light/
Green Mountain Power http://www.greenmountainpower.com/

**Comment by dfcoffin** [comment]
Closed 7a4004d6e75a46a64d9acdd3ecd67a2782df83ee
