### ISSUE TITLE
The website contains several spelling and grammatical errors 

### ISSUE THREAD

**Issue by dfcoffin** [green-button/green-button.github.io#61]
An example is the following which appears on the "build" webpage contains the following errors:

     *  The phrase "will will" s/b "will"
     *  XML (an acronym) appears in low-case the second time it is used

    The Tools SDK provides a set of stand-alone tools to help you work with Green Button XML data. Written primarily in Visual Basic and using Excel macros, you will
    will be able to see simple code that parses Green Button xml and validates appropriate things like time and resource values.  These tools were used in the creation
    of the on-line <a href="http://www.greenbuttondata.org/greentest.aspx">Green Button validator</a>, where you can test your exported Green Button files for correctness.

**Comment by jateeter** [comment]
Closed ref: https://github.com/green-button/green-button.github.io/commit/b36aa1913d373122ffca0275cad2c672fcb3ec92  (Note that a full  proof read is needed and additional issues will likely be generated)
