### ISSUE TITLE
The soon to be announced Green Button Alliance needs to have a link to their site added to the home page

### ISSUE THREAD

**Issue by dfcoffin** [green-button/green-button.github.io#63]
The Green Button Alliance a non-profit 501(c)(3) organization has been formed as a separate entity under the UCAIug organization as a marketing, education, and testing/certification organization to further the Green Button Initiative.  It will be announced on Feb 6, 2015 at the "Birth of the Green Button Ecosystem" event and needs to have a presence on the greenbuttondata.org website.

**Comment by jateeter** [comment]
?? how is this to be addressed - is it simply a footer change or are there additional elements of the site that are intended to be mutated?

**Comment by jateeter** [comment]
Note that this DoE site:  https://www.data.gov/energy/welcome-green-button  has the same TM issues.

**Comment by MartyBurns** [comment]
Done
